export const INITIAL_PRODUCTS = [
  {
    id: 'p1',
    name: 'Premium Urea Fertilizer (45kg)',
    category: 'Fertilizers',
    price: 1200,
    seller: 'Kisan Agro Kendra',
    location: '2.5 km away',
    stock: 50,
    rating: 4.8,
    reviews: 124,
    image: 'https://images.unsplash.com/photo-1628187843336-70e0f80b95d0?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
    description: 'High-quality urea fertilizer suitable for all crops. Enhances vegetative growth.',
    isDeal: true,
  },
  {
    id: 'p2',
    name: 'Hybrid Tomato Seeds (10g)',
    category: 'Seeds',
    price: 450,
    seller: 'GreenLife Seeds',
    location: '4.1 km away',
    stock: 200,
    rating: 4.5,
    reviews: 89,
    image: 'https://images.unsplash.com/photo-1592841200221-a6898f307ba0?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
    description: 'High-yield, disease-resistant tomato seeds. Expected germination rate 95%.',
    isDeal: false,
  },
  {
    id: 'p3',
    name: 'Heavy Duty Hand Trowel',
    category: 'Equipment',
    price: 350,
    seller: 'Ramesh Hardware',
    location: '1.2 km away',
    stock: 15,
    rating: 4.2,
    reviews: 45,
    image: 'https://images.unsplash.com/photo-1416879598555-46af08d6d8db?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
    description: 'Durable steel hand trowel with ergonomic grip. Essential for planting and weeding.',
    isDeal: false,
  },
  {
    id: 'p4',
    name: 'Organic Neem Oil Pesticide (1L)',
    category: 'Pesticides',
    price: 600,
    seller: 'EcoFarm Solutions',
    location: '6.8 km away',
    stock: 30,
    rating: 4.9,
    reviews: 210,
    image: 'https://images.unsplash.com/photo-1622383563227-04401ab4e5eA?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
    description: '100% organic neem oil extract. Effective against aphids, mites, and whiteflies.',
    isDeal: true,
  },
  {
    id: 'p5',
    name: 'DAP Fertilizer (50kg)',
    category: 'Fertilizers',
    price: 1350,
    seller: 'Kisan Agro Kendra',
    location: '2.5 km away',
    stock: 100,
    rating: 4.6,
    reviews: 150,
    image: 'https://images.unsplash.com/photo-1588607310433-89bd24e5a9ee?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
    description: 'Di-ammonium Phosphate. Excellent source of Phosphorus and Nitrogen.',
    isDeal: false,
  },
  {
    id: 'p6',
    name: 'Battery Operated Knapsack Sprayer (16L)',
    category: 'Equipment',
    price: 3200,
    seller: 'AgriTech Tools',
    location: '12 km away',
    stock: 8,
    rating: 4.7,
    reviews: 67,
    image: 'https://images.unsplash.com/photo-1598410291771-831825fa848d?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60',
    description: 'Rechargeable battery-operated sprayer. Lasts 6 hours on a single charge.',
    isDeal: false,
  }
];

export const CATEGORIES = ['All', 'Fertilizers', 'Seeds', 'Equipment', 'Pesticides', 'Crops'];

export const INITIAL_ORDERS = [
  {
    id: 'ORD-849204',
    date: '2026-03-25T10:30:00Z',
    total: 1650,
    status: 'Delivered',
    items: [
      { name: 'Premium Urea Fertilizer (45kg)', qty: 1, price: 1200 },
      { name: 'Hybrid Tomato Seeds (10g)', qty: 1, price: 450 }
    ],
    deliveryEstimate: 'Delivered on Mar 26',
  }
];
